name: Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Release Tag'
        type: string
      changelog:
        description: 'Changelog'
        type: string
      draft:
        description: 'Draft'
        type: boolean
      prerelease:
        description: 'Pre-release'
        type: boolean

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Copy LICENSE
      run: cp LICENSE include/bitstream/LICENSE
    - name: Copy NETSTACKLICENSE
      run: cp NETSTACKLICENSE include/bitstream/NETSTACKLICENSE
    - name: Create VERSION.txt
      run: echo "${{ inputs.tagName }}" > include/bitstream/VERSION.txt
    - name: Install zip
      run: |
        sudo apt update
        sudo apt install -y zip
    - name: Zip headers
      run: zip -r BitStream.zip include/bitstream
    - name: Tar headers
      run: tar czvf BitStream.tar.gz include/bitstream
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BitStream.zip
          BitStream.tar.gz
        tag_name: ${{ inputs.tagName }}
        body: ${{ inputs.changelog }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        fail_on_unmatched_files: true